spring:
  application:
    name: zookeeper-backend-service-demo
  cloud:
    zookeeper:
      discovery:
        
        metadata:
          tenant-bound: yes
          tenant:
            - tenant1
            - tenant2

server:
  port: 8081